#!/bin/sh
#
# build.sh -- build libSDL2.a and sdl2.library.
#
# Part of SDL2.Library-Amiga-m68K.
# Copyright (c) 2026 JennaScvl
#
# This software is provided 'as-is', without any express or implied
# warranty. See LICENCE.MD (zlib License) for the full terms.
#
# Everything is in this repository -- a fresh clone builds without
# fetching anything but the toolchain image.
#
# Usage:
#   ./build.sh            build libSDL2.a if needed, then sdl2.library
#   ./build.sh sdl2       build libSDL2.a only
#   ./build.sh lib        build sdl2.library only (reuse libSDL2.a)
#   ./build.sh test       also build the test application
#   ./build.sh dev        build under a unique name for iteration (see below)
#   ./build.sh dist       assemble dist/ for handing to other developers
#   ./build.sh clean      remove build products
#
# Environment:
#   IMAGE   cross-toolchain image. Default amigadev/crosstools:m68k-amigaos
#   DEPLOY  optional directory to copy the results into (e.g. a WinUAE
#           shared folder)
#   JOBS    parallelism for the SDL2 build (default 4)
#
set -e

HERE=$(cd "$(dirname "$0")" && pwd)
IMAGE=${IMAGE:-amigadev/crosstools:m68k-amigaos}
JOBS=${JOBS:-4}

NIX=/opt/m68k-amigaos/m68k-amigaos/libnix
GCCLIB=/opt/m68k-amigaos/lib/gcc/m68k-amigaos/6.5.0b/libm020

run() {
    MSYS_NO_PATHCONV=1 docker run --rm -v "$HERE:/work" -w /work "$IMAGE" \
        sh -c "$1"
}

# ---------------------------------------------------------------------
# The library version tracks SDL's, read from the headers rather than
# maintained by hand -- the two can then never disagree.
#
# AmigaOS gives a library a version/revision PAIR, and the VERSION half
# is what OpenLibrary's second argument tests with >=. SDL's major is
# always 2, so putting that in the version would make the gate useless:
# every release would satisfy it.
#
# SDL's MINOR goes in the version instead, and the patchlevel in the
# revision. SDL 2.33.0 becomes "sdl2.library 33.0", and
#
#     OpenLibrary("sdl2.library", 33)
#
# means a real thing: "I need at least SDL 2.33". It stays monotonic for
# the life of SDL2. The full three-part release is in the ID string, and
# SDL2_GetVersion() reports it at runtime.
#
# The awk must anchor on #define: SDL_MAJOR_VERSION also appears inside
# the body of SDL_VERSION_ATLEAST, and matching that yields "<".
# ---------------------------------------------------------------------
sdl_ver_part() {
    awk -v want="$1" '$1 == "#define" && $2 == want { print $3; exit }' \
        "$HERE/include/SDL_version.h"
}

SDL_MAJOR=$(sdl_ver_part SDL_MAJOR_VERSION)
LIB_VERSION=$(sdl_ver_part SDL_MINOR_VERSION)
LIB_REVISION=$(sdl_ver_part SDL_PATCHLEVEL)

sdl_version() {
    echo "$SDL_MAJOR.$LIB_VERSION.$LIB_REVISION"
}

build_sdl2() {
    echo "==> libSDL2.a (SDL $(sdl_version)) -- slow the first time"
    run "make -j$JOBS libSDL2.a"
    [ -f "$HERE/libSDL2.a" ] || { echo "libSDL2.a was not produced" >&2; exit 1; }
}

build_lib() {
    # -----------------------------------------------------------------
    # THE LIBRARY NAME.
    #
    # Shipping builds are plain "sdl2.library" -- that is what a program
    # asks OpenLibrary for.
    #
    # "dev" builds get sdl2_r<n>.library instead, and that is not
    # cosmetic. AmigaOS keeps a library resident after its last client
    # closes, and a run that HANGS never closes it at all, so the next
    # run silently gets the PREVIOUS jump table and any newly added
    # export calls off the end of it and crashes. The only cure is a
    # reboot.
    #
    # exec's OpenLibrary finds a resident library BY NAME (verified
    # against Kickstart 3.1: OpenLibrary is LVO -552 and is Forbid,
    # FindName on SysBase->LibList, a version check, then the library's
    # own Open; FindName compares bytes to the NUL, no path stripping).
    # So a uniquely named build simply is not what a pinned corpse
    # answers to. Anyone iterating on this library wants that.
    # -----------------------------------------------------------------
    if [ "$DEV" = 1 ]; then
        n=$(cat "$HERE/build/DEVNUM" 2>/dev/null || echo 0)
        n=$((n + 1))
        mkdir -p "$HERE/build"
        echo "$n" > "$HERE/build/DEVNUM"
        LIBNAME="sdl2_r$n.library"
    else
        LIBNAME="sdl2.library"
    fi

    mkdir -p "$HERE/build"
    # Every previous library, not just the dev-named ones: switching
    # between "dev" and a shipping build would otherwise leave the other
    # one behind, and DEPLOY would copy both.
    rm -f "$HERE"/build/*.library

    cat > "$HERE/build/sdl2version.h" <<EOF
/* Generated by build.sh -- do not edit. */
#define SDL2LIB_VERSION   $LIB_VERSION
#define SDL2LIB_REVISION  $LIB_REVISION
#define SDL2LIB_VERSTRING "$LIB_VERSION.$LIB_REVISION"
#define SDL2LIB_NAME      "$LIBNAME"
#define SDL2LIB_SDLVER    "$(sdl_version)"
EOF

    echo "==> $LIBNAME $LIB_VERSION.$LIB_REVISION (SDL $(sdl_version))"

    run "
    set -e

    # Caller-side inlines from the .fd.
    #
    # MODE 40 OR 41 ONLY. fd2pragma --special 43 emits POSITIVE LVO
    # offsets (jsr 114(a6) instead of jsr -114(a6)), so calls land just
    # above the library base and execute whatever is there. It presents
    # as a Line-1111 crash in a program with no A-line instruction in it.
    fd2pragma --special 40 --infile library/sdl2_lib.fd \\
              --clib library/clib/sdl2_protos.h >/dev/null
    mv sdl2.h build/sdl2.h 2>/dev/null || true

    for c in sdl2lib sdl2api sdl2probes sdl2table sdl2crt; do
        m68k-amigaos-gcc -m68030 -O2 -fomit-frame-pointer -mcrt=nix20 \\
            -I$NIX/include -Iinclude -Ibuild -Ilibrary \\
            -c library/\$c.c -o build/\$c.o
    done

    # GNU ld, NOT vlink: libnix's ADD2LIST puts the export table in
    # section .list___FuncTable__, and only ld's SORT_BY_NAME rules
    # gather those. vlink drops them silently, leaving the table
    # truncated to libinit's own four entries.
    m68k-amigaos-ld -o build/$LIBNAME \\
        $NIX/lib/libinit.o \\
        build/sdl2lib.o build/sdl2api.o build/sdl2probes.o \\
        build/sdl2table.o build/sdl2crt.o \\
        --start-group \\
            libSDL2.a $NIX/lib/libnix20.a $NIX/lib/libnix.a \\
            $NIX/lib/libm.a /opt/m68k-amigaos/m68k-amigaos/lib/libamiga.a \\
            $GCCLIB/libgcc.a \\
        --end-group
    "
    [ -f "$HERE/build/$LIBNAME" ] || { echo "missing: $LIBNAME" >&2; exit 1; }
}

build_test() {
    echo "==> test application"
    # Links NOTHING of SDL2 -- every call goes through the jump table --
    # but it needs SDL2's headers so caller and library agree on struct
    # layout. They must: the .fd fixes registers, not layout.
    run "m68k-amigaos-gcc -m68030 -O1 -mcrt=nix20 -Wall \\
         -Ibuild -Ilibrary -Iinclude \\
         -o build/sdl2test test/sdl2test.c"
    [ -f "$HERE/build/sdl2test" ] || { echo "missing: sdl2test" >&2; exit 1; }
    # The config and the sound the test plays. cuckoo.raw is generated
    # from cuckoo.wav by tools/wav2raw.py and committed, so the test is
    # runnable from a clone without needing Python.
    cp "$HERE/test/sdl2test.cfg" "$HERE/test/cuckoo.raw" "$HERE/build/"
}

build_dist() {
    D="$HERE/dist"
    rm -rf "$D"
    mkdir -p "$D/libs" "$D/sdk/include" "$D/sdk/clib" "$D/sdk/fd"

    cp "$HERE/build/sdl2.library" "$D/libs/"
    cp -r "$HERE"/include/*.h        "$D/sdk/include/"
    cp "$HERE/build/sdl2.h"          "$D/sdk/include/"
    cp "$HERE/library/clib/sdl2_protos.h" "$D/sdk/clib/"
    cp "$HERE/library/sdl2_lib.fd"   "$D/sdk/fd/"
    cp "$HERE/PORTING.md" "$HERE/LICENCE.MD" "$D/"

    cat > "$D/README" <<EOF
sdl2.library $LIB_VERSION.$LIB_REVISION -- SDL $(sdl_version) for AmigaOS 3

  libs/sdl2.library        copy to LIBS: (or keep beside your program)
  sdk/include/             SDL2 headers, plus sdl2.h (the inlines)
  sdk/clib/                prototypes
  sdk/fd/                  function descriptions, if you need to
                           regenerate inlines for another compiler

See PORTING.md for how to build against it.
EOF
    echo "==> dist/ assembled"
    find "$D" -type f | sed "s|$D|  dist|" | sort
}

DEV=0
case "${1:-}" in
clean)
    rm -rf "$HERE/build" "$HERE/dist"
    run "make clean" || true
    echo "cleaned"
    exit 0
    ;;
sdl2)
    build_sdl2
    exit 0
    ;;
lib)
    [ -f "$HERE/libSDL2.a" ] || { echo "run ./build.sh sdl2 first" >&2; exit 1; }
    build_lib
    ;;
test)
    [ -f "$HERE/libSDL2.a" ] || build_sdl2
    build_lib
    build_test
    ;;
dev)
    DEV=1
    [ -f "$HERE/libSDL2.a" ] || build_sdl2
    build_lib
    build_test
    ;;
dist)
    [ -f "$HERE/libSDL2.a" ] || build_sdl2
    build_lib
    build_dist
    exit 0
    ;;
*)
    [ -f "$HERE/libSDL2.a" ] || build_sdl2
    build_lib
    ;;
esac

ls -l "$HERE/build"

if [ -n "${DEPLOY:-}" ]; then
    mkdir -p "$DEPLOY"
    rm -f "$DEPLOY"/sdl2_r*.library
    cp "$HERE"/build/*.library "$DEPLOY/"
    [ -f "$HERE/build/sdl2test" ] && cp "$HERE/build/sdl2test" \
        "$HERE/build/sdl2test.cfg" "$HERE/build/cuckoo.raw" "$DEPLOY/"
    echo "deployed to $DEPLOY"
fi
